name: events
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  google_fonts: ^6.2.1
  flutter_svg_provider: ^1.0.7
  toggle_switch: ^2.3.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  animated_toggle_switch: ^0.8.5
  firebase_core: ^2.25.5  # Use the latest stable version
  firebase_auth: ^4.17.5 # Use the latest stable version
  cloud_firestore: ^4.15.5 # Use the latest stable version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
