// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPCYQjLPjH5Cq0cbdh7htH4nZt-u8VP5A',
    appId: '1:531231672619:web:3b269495c1db5b50335d6e',
    messagingSenderId: '531231672619',
    projectId: 'device-streaming-9b5c6cc1',
    authDomain: 'device-streaming-9b5c6cc1.firebaseapp.com',
    storageBucket: 'device-streaming-9b5c6cc1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-7Lc5WzeFmDfo5ig7qs8Qi1YaGxfSEiM',
    appId: '1:962892648759:android:109d0aa3968409b2fd4ab2',
    messagingSenderId: '962892648759',
    projectId: 'events-app-new',
    storageBucket: 'events-app-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE1z8SeYxYW7wKSZxR2AfPgLgmBBnpPRM',
    appId: '1:531231672619:ios:94fdca9e839557f8335d6e',
    messagingSenderId: '531231672619',
    projectId: 'device-streaming-9b5c6cc1',
    storageBucket: 'device-streaming-9b5c6cc1.firebasestorage.app',
    iosBundleId: 'com.example.events',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE1z8SeYxYW7wKSZxR2AfPgLgmBBnpPRM',
    appId: '1:531231672619:ios:94fdca9e839557f8335d6e',
    messagingSenderId: '531231672619',
    projectId: 'device-streaming-9b5c6cc1',
    storageBucket: 'device-streaming-9b5c6cc1.firebasestorage.app',
    iosBundleId: 'com.example.events',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPCYQjLPjH5Cq0cbdh7htH4nZt-u8VP5A',
    appId: '1:531231672619:web:cd10c56c0322ecb2335d6e',
    messagingSenderId: '531231672619',
    projectId: 'device-streaming-9b5c6cc1',
    authDomain: 'device-streaming-9b5c6cc1.firebaseapp.com',
    storageBucket: 'device-streaming-9b5c6cc1.firebasestorage.app',
  );

}